---
- name: create directory for unarchive backend files
  become: true
  file:
    path: /unarchive
    state: directory
- name: copy files to unarchive dir
  copy:
    src: artifact.tar.gz
    dest: /unarchive
- name : unarchive files
  unarchive:
      src: artifact.tar.gz
      dest: /unarchive
- name: install npm
  become: true
  shell: |
    cd /unarchive
    npm install
- name: start services
  become: true
  shell: |
    cd /unarchive
    pm2 stop default
    pm2 start npm -- start