---

- name: copy files to unarchive dir
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu
- name : unarchive files
  unarchive:
      src: artifact.tar.gz
      dest: /home/ubuntu
- name: install npm
  become: true
  shell: |
    cd /home/ubuntu
    npm install
- name: start services
  become: true
  shell: |
    cd /home/ubuntu
    pm2 stop default
    pm2 start npm -- start
