---

- name: copy files to unarchive dir
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu
- name : unarchive files
  unarchive:
      src: artifact.tar.gz
      dest: /home/ubuntu
- name: install npm
  become: true
  shell: |
    cd /home/ubuntu
    npm install
- name: start services
  become: true
  shell: |
    cd /home/ubuntu
    sudo apt -y update && apt -y upgrade
    curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
    apt-get install -y nodejs
    npm install -g webpack-dev-server
    npm run build
    pm2 stop default
    pm2 start npm -- start
